#pragma once
#include "Types.h"

inline Level ALL_LEVELS[] = {
	{"\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWW WWWWWWWW\
WWWWWW  WWWWWWWW\
WWWWWW WWWWWWWWW\
WWWWWW   WWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW", 16, "UDLR", {7, 4}, {8, 7}
	},
	{"\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWW WWWWWWW\
WWWWWWWW  WWWWWW\
WWWWW   W WWWWWW\
WWWWWWW   WWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW", 16, "UDLR", {5, 6}, {8, 4}
	},
{"\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWW   WWWWWWWW\
WWWWW W  WWWWWWW\
WWWWW WW  WWWWWW\
WWWWW W   WWWWWW\
WWWWW WWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW", 16, "UDLR", {5, 7}, {7, 6}
},
{"\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWW WWWWWWWWWW\
WWWWW  H  WWWWWW\
WWWWWWWWW WWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW", 16, "UDLR>", {5, 4}, {9, 6}
},
{"\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWW H WWWWWWW\
WWWWWW W WWWWWWW\
WWWWWWWW WWWWWWW\
WWWWWW   WWWWWWW\
WWWWWW WWWWWWWWW\
WWWWWW H WWWWWWW\
WWWWWW    WWWWWW\
WWWWWWW  WWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW", 16, "UDLR^~<>", {6, 3}, {9, 8}
},
{"\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWWWWWWWWWWWW\
WWWWWW H WWWWWWW\
WWWW H WHWWWWWWW\
WWWWWWWW H WWWWW\
WWWWWWWWWW WWWWW\
WWWWWWWW H WWWWW\
WWWWWW WHWWWWWWW\
WWWWWW   WWWWWWW\
WWWWWWWWWWWWWWWW", 16, "UDLR^~<>", {4, 4}, {6,8}
}
};
